name: Scratchip Binary CI
language: generic
env:
  - MILL_VERSION=0.10.0
before_deploy:
  - curl --fail -L -o mill https://github.com/lihaoyi/mill/releases/download/$MILL_VERSION/$MILL_VERSION-assembly
  - chmod +x mill
  - make verilog
  - tar czvf cache.tar.gz .cache
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - cache.tar.gz
    - mill
  skip_cleanup: true
  on:
    tags: true
